# Copyright 2016 Erik Van Hamme
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Descriptor file for CubeF4 V1.11.0.
cube 'f4', 'v1.11.0', 'STM32Cube_FW_F4_V1.11.0' do

  # -- Base Component Section ------------------------------------------------------------------------------------------

  # [ARM] CMSIS component as delivered by ARM.
  component 'cmsis' do
    sys_inc 'Drivers/CMSIS/Include'
  end

  # [ARM] DSP library to use DSP functions with the CM4.
  component 'dsp' do
    depends 'cmsis'
    define 'ARM_MATH_CM4'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/CommonTables/arm_common_tables.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/CommonTables/arm_const_structs.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_conj_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_conj_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_conj_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_dot_prod_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_squared_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_real_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_real_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions/arm_cmplx_mult_real_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_reset_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_reset_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_pid_reset_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_sin_cos_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions/arm_sin_cos_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_cos_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_cos_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_cos_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sin_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sin_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sin_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sqrt_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sqrt_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_add_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_add_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_add_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_inverse_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_inverse_f64.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_fast_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_fast_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_mult_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_scale_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_scale_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_scale_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_sub_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_sub_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_sub_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_trans_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_trans_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions/arm_mat_trans_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_max_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_mean_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_min_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_power_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_rms_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_rms_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_rms_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_std_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_std_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_std_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_var_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_var_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions/arm_var_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_copy_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_fill_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_float_to_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_float_to_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_float_to_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q15_to_float.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q15_to_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q15_to_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q31_to_float.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q31_to_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q31_to_q7.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q7_to_float.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q7_to_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/SupportFunctions/arm_q7_to_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_bitreversal.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix2_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix4_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_cfft_radix8_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_dct4_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_fast_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_fast_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_init_f32.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_init_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_init_q31.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_q15.c'
    sys_src 'Drivers/CMSIS/DSP_Lib/Source/TransformFunctions/arm_rfft_q31.c'
  end

  # [ST] HAL library component.
  component 'hal' do
    depends 'cmsis'
    define 'USE_HAL_DRIVER'
    sys_inc 'Drivers/STM32F4xx_HAL_Driver/Inc'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c'
    sys_src 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c'
    template 'Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_conf_template.h', 'auto'
    template 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_msp_template.c'
    template 'Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_timebase_tim_template.c'
  end

  # -- Chip Support Section --------------------------------------------------------------------------------------------

  # [ST] Common declarations for chip family.
  chipfamily 'stm32f4xx' do
    depends 'cmsis'
    flash_base 0x08000000
    sram_base 0x20000000
    ccm_base 0x10000000
    conditional do
      condition_option_set 'fpu'
      define '__FPU_PRESENT', 1
    end
    sys_inc 'Drivers/CMSIS/Device/ST/STM32F4xx/Include'
    template 'Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c', 'auto'
  end

  # [ST] 407xE chip.
  chip 'stm32f407xe' do
    depends 'stm32f4xx'
    flash '512k'
    sram '128k'
    ccm '64k'
    define 'STM32F407xx'
    sys_src 'Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f407xx.s'
  end

  # [ST] 407xG chip.
  chip 'stm32f407xg' do
    depends 'stm32f4xx'
    flash '1M'
    sram '128k'
    ccm '64k'
    define 'STM32F407xx'
    sys_src 'Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f407xx.s'
  end

  # [ST] 417xE chip.
  chip 'stm32f417xe' do
    depends 'stm32f4xx'
    flash '512k'
    sram '128k'
    ccm '64k'
    define 'STM32F417xx'
    sys_src 'Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f417xx.s'
  end

  # [ST] 417xE chip.
  chip 'stm32f417xg' do
    depends 'stm32f4xx'
    flash '1M'
    sram '128k'
    ccm '64k'
    define 'STM32F417xx'
    sys_src 'Drivers/CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc/startup_stm32f417xx.s'
  end

  # -- Board Support Section -------------------------------------------------------------------------------------------

  # [ST] Common component for board support packages.
  component 'bsp_common' do
    sys_inc 'Drivers/BSP/Components/Common'
  end

  # [ST] Component driver for cs43l22 chip.
  component 'cs43l22' do
    sys_inc 'Drivers/BSP/Components/cs43l22'
    sys_src 'Drivers/BSP/Components/cs43l22/cs43l22.c'
  end

  # [ST] Component driver for lis302dl chip.
  component 'lis302dl' do
    sys_inc 'Drivers/BSP/Components/lis302dl'
    sys_src 'Drivers/BSP/Components/lis302dl/lis302dl.c'
  end

  # [ST] Component driver for lis3dsh chip.
  component 'lis3dsh' do
    sys_inc 'Drivers/BSP/Components/lis3dsh'
    sys_src 'Drivers/BSP/Components/lis3dsh/lis3dsh.c'
  end

  # [ST] Board support package for STM32F4-Discovery board.
  board 'stm32f4-discovery' do
    define 'HSE_SPEED', '8000000'
    depends 'stm32f407xg'
    depends 'hal'
    depends 'bsp_common'
    depends 'cs43l22'
    depends 'lis302dl'
    depends 'lis3dsh'
    depends 'stm32_audio'
    sys_inc 'Drivers/BSP/STM32F4-Discovery'
    sys_src 'Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c'
    sys_src 'Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c'
    sys_src 'Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_audio.c'
  end

  # -- Middleware Support Section --------------------------------------------------------------------------------------

  # [ST] PDM Filter audio addon.
  component 'stm32_audio' do
    sys_inc 'Middlewares/ST/STM32_Audio/Addons/PDM'
    conditional do
      condition_option_set 'fpu'
      lib 'Middlewares/ST/STM32_Audio/Addons/PDM/libPDMFilter_CM4F_GCC.a'
    end
    conditional do
      condition_option_unset 'fpu'
      lib 'Middlewares/ST/STM32_Audio/Addons/PDM/libPDMFilter_CM4_GCC.a'
    end
  end
end